### ISSUE TITLE
Rethink Serde Integration

### ISSUE THREAD

**Issue by asonix** [zshipko/rust-kv#2]
I'm currently using this crate in a project, and I've run into an issue with how you've designed Serde integration, and I also have a solution that may be interesting to you.

I wanted to serialize data stored in LMDB with bincode, but firstly, there's no documentation for how to do that, so I read through the source and found that you had a custom `Data` type for using bincode as an encoding. This isn't great, since the custom type doesn't provide good mechanisms for interacting with custom data structures.

The way I worked around this was to implement Encoding for a custom type that wraps a generic. Here is a general overview of how it works

```rust
pub struct BincodeEncoding<T>(pub T);

impl<T: DeserializeOwned + Serialize> Encoding for BincodeEncoding<T> {
    fn encode_to<W: Write>(&self, w: &mut W) -> Result<(), Error> {
        bincode::serialize_into(w, &self.0).map_err(|e| {
            // do required error mapping
        })
    }

    fn decode_from<R: Read>(r: &mut R) -> Result<Self, Error> {
        bincode::deserialize_from(r).map(BincodeEncoding).map_err(|e| {
            // do required error mapping
        })
    }
}
```

This allows for serialization and deserialization of user-provided types in LMDB, and can be easily replicated for other serde-compatible crates.

**Comment by zshipko** [comment]
@asonix - I agree, serde/bincode integration is definitely something that needs to be improved upon.

Feel free to send a pull request with what you've implemented, otherwise I will see how I can integrate the above code into the project.

**Comment by asonix** [comment]
I'll go ahead and start working on a PR, I've actually created an example app using KV with serde: https://github.com/asonix/kv-testing

I think I'll just merge what I've done here into a branch of KV and see what you think

**Comment by zshipko** [comment]
Wow, that is great! 

I've also just done a rough port of your code from the earlier comment, on the [better-bincode branch](https://github.com/zshipko/rust-kv/tree/better-bincode), which also includes some more helpful documentation.

Maybe we can combine our efforts somehow? I'd also be happy to go with your implementation, since it seems like you've spent some time working on this already!

**Comment by asonix** [comment]
Oh, it looks like we were both working on the same thing! You've written some documentation, which is better than what I've done, but I've touched bincode, cbor, and json in my branch. Let me open a PR real quick and we can compare changes

**Comment by zshipko** [comment]
Okay, sounds good. I made that branch to see how that would work but didn't realize you had done the same thing for all the supported encodings (+more!).

It seems easiest to just copy the documentation I've added to your branch.

**Comment by zshipko** [comment]
Alright, everything is merged. I will let this sit for a few hours before closing then make a new release at the end of the day.

Let me know if you think of anything else that you feel should be included in the meantime. 

And again thanks for the contributions!

**Comment by zshipko** [comment]
`kv` has now been updated to version 0.6 on crates.io
