### ISSUE TITLE
Support for multi-tree transactions

### ISSUE THREAD

**Issue by fooker** [zshipko/rust-kv#22]
Would be cool to allow a transaction to span over multiple buckets. This would allow to atomically move an element from one bucket to another. `sled` already has support for this: https://docs.rs/sled/0.34.6/sled/transaction/trait.Transactional.html#foreign-impls

**Comment by zshipko** [comment]
I've added support for transactions with 2 and 3 buckets: https://github.com/zshipko/rust-kv/commit/3b1cb31af7a7c9d944ed6b835edbfd9f8ce00e14 and am publishing a new release right now.
