### ISSUE TITLE
Passing keys by reference

### ISSUE THREAD

**Issue by fooker** [zshipko/rust-kv#23]
Methods on `Bucket` receiving a `Key` parameter should do so by accepting a reference to the key. This would allow to use the same key in multiple operations without cloning.

`sled` accepts an `AsRef<[u8]>` for the underlying operations. By doing the same in `kv`, it can support references without changing the API for existing code.

**Comment by zshipko** [comment]
What type are you using for keys? For `Integer` or  `&str`/ `&[u8]` keys you should be able to pass the same key to multiple operations.

For example, something like this should work fine.
```
let bucket = store.bucket::<&str, Raw>(None).unwrap();
let key = "abc";    
bucket.set(key, b"123").unwrap(); 
bucket.remove(key).unwrap();
```

For more complex key types it might make sense to use `&str` as the key type and do the encoding yourself to avoid encoding the same thing multiple times.

If you had something else in mind I'm happy to discuss.

**Comment by fooker** [comment]
Currently, I'm using `kv::Raw`. In addition, I store the `Bucket` in a struct. So having a reference as defined key type does not really work here.
