### ISSUE TITLE
Config::temporary unused

### ISSUE THREAD

**Issue by werner291** [zshipko/rust-kv#38]
Hello,

I was a bit confused over the purpose of `Config::temporary`... The config value seems entirely unused?

Also, for the "flush frequency", does that flush happen in the background as well? In a separate thread or on some kinda schedule, or only when actually modifying the store?

**Comment by zshipko** [comment]
temporary is used here: https://github.com/zshipko/rust-kv/blob/b2f356080beb6b6bc3b0b5012721382507108c9f/src/config.rs#L112
The flush interval value is passed directly to `sled` and has something to do with how frequently flush is used when writing to disk.

**Comment by werner291** [comment]
Huh, must have missed that. Apologies.
